# Generated by Django 3.2 on 2022-08-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='department',
        ),
    ]
