# Generated by Django 3.2 on 2022-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_rename_dept_name_department_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=120),
        ),
    ]
